plots:
  # --- Example Bar Plot (Termination Reasons) ---
  - type: bar
    enabled: true # Enable/disable this specific plot
    source: summary # Use data from the summary DataFrame
    variable: termination_reason # The column in the summary to count/group by
    output_filename: fig1_termination_reason_distribution.png # Specific output name
    config:
      title: Termination Reason Distribution
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Episode Group [-]
      xlabel_fontsize: 16
      ylabel: Count [-]
      ylabel_fontsize: 16
      # xmin: null # Not typically used for category bar plots
      # xmax: null
      ymin: 0 # Start y-axis at 0
      ymax: null # Auto scale max y
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null # Auto ticks for categories
      num_yticks: null
      show_legend: true
      legend_pos: outside # 'best', 'upper left', 'outside', etc.
      legend_fontsize: 'medium' # 'xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large' or a number (e.g., 8, 10, 12)
      grid_on: false
      group_size: 1000 # Size for group by episodes
      cmap: tab20 # Colormap for stacked bars
      bar_width: 0.8
  # --- Example Line Plot (Total Reward) ---
  - type: line
    enabled: true
    source: summary # Use data from the summary DataFrame
    x_variable: episode # Column for x-axis
    y_variable: total_reward # Column for y-axis
    output_filename: fig2_cumulative_reward_per_episode.png
    config:
      title: Cumulative Reward per Episode
      title_fontsize: 14
      figsize_w: 12
      figsize_h: 6
      xlabel: Episode [-]
      xlabel_fontsize: 12
      ylabel: Total Reward [-]
      ylabel_fontsize: 12
      xmin: null # Auto scale min x
      xmax: null # Auto scale max x
      ymin: null # Auto scale min y
      ymax: null # Auto scale max y
      tick_fontsize: 10
      xtick_rotation: 30
      num_xticks: null   # Approx number of desired x-ticks
      num_yticks: null   # Approx number of desired y-ticks
      show_legend: false # Only one line, legend not needed
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.0
      marker_style: 'o' # Style: '.', ',', 'o', 'v', '^', etc. or '' for none
      marker_size: 3
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null # Optional: list like ['stabilized', 'time_limit'] or null to include all
  # --- Example Line Plot (Episode Time) ---
  - type: line
    enabled: true
    source: summary
    x_variable: episode
    y_variable: episode_time
    output_filename: fig3_episode_duration_per_episode.png
    config:
      title: Episode Duration per Episode
      title_fontsize: 14
      figsize_w: 12
      figsize_h: 6
      xlabel: Episode [-]
      xlabel_fontsize: 12
      ylabel: Duration [s]
      ylabel_fontsize: 12
      xmin: null
      xmax: null
      ymin: 0
      ymax: null
      tick_fontsize: 10
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      show_legend: false
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.5
      marker_style: 'o'
      marker_size: 3
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null
  # --- Example Line Plot (Performance) ---
  - type: line
    enabled: true
    source: summary
    x_variable: episode
    y_variable: performance
    output_filename: fig4_performance_per_episode.png
    config:
      title: Performance per Episode
      title_fontsize: 14
      figsize_w: 12
      figsize_h: 6
      xlabel: Episode [-]
      xlabel_fontsize: 12
      ylabel: Performance [-/s]
      ylabel_fontsize: 12
      xmin: null
      xmax: null
      ymin: 0
      ymax: null
      tick_fontsize: 10
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      show_legend: false
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.0
      marker_style: 'o'
      marker_size: 3
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Angle) ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: pendulum_angle
    output_filename: fig5_heatmap_time_vs_pendulum_angle.png
    config:
      title: Heatmap - Time vs Pendulum Angle
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Pendulum Angle [rad]
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -0.1
      ymax: 0.1
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency # Colorbar label
      clabel_fontsize: 14
      cmin: null
      cmax: 50000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 500 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Angle) stabilized ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: pendulum_angle
    output_filename: fig6_heatmap_time_vs_pendulum_angle(stabilized).png
    config:
      title: Heatmap - Time vs Pendulum Angle (stabilized)
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Pendulum Angle [rad]
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: null
      ymax: null
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency # Colorbar label
      clabel_fontsize: 14
      cmin: null
      cmax: 2000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 500 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: ['stabilized']
  # --- Example Heatmap (Time vs  Angular Velocity) ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: pendulum_velocity
    output_filename: fig7_heatmap_time_vs_pendulum_velocity.png
    config:
      title: Heatmap - Time vs Angular Velocity
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Pendulum Velocity (rad/s)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -1
      ymax: 1
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null 
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: 50000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 1000 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: null # Optional: filter episodes before aggregating data
  # --- Example Heatmap (Angle vs Angular Velocity) ---
  - type: heatmap
    enabled: true
    source: detailed
    x_variable: pendulum_angle
    y_variable: pendulum_velocity
    output_filename: fig8_heatmap_pendulum_angle_vs_pendulum_velocity.png
    config:
      title: Heatmap - Angle vs Angular Velocity
      title_fontsize: 18
      figsize_w: 16
      figsize_h: 12
      xlabel: Pendulum Angle (rad)
      xlabel_fontsize: 16
      ylabel: Pendulum Velocity (rad/s)
      ylabel_fontsize: 16
      xmin: -0.1
      xmax: 0.1
      ymin: -0.1
      ymax: 0.1
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: 5000
      cmap: hot
      bins: 1000
      log_scale: false
      grid_on: false
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Cart Position) ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: cart_position
    output_filename: fig9_heatmap_time_vs_cart_position.png
    config:
      title: Heatmap - Time vs Cart Position
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Cart Position (m)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -5.0
      ymax: 5.0
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: 50000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 500 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Cart Position) stabilized ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: cart_position
    output_filename: fig10_heatmap_time_vs_cart_position(stabilized).png
    config:
      title: Heatmap - Time vs Cart Position (stabilized)
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Cart Position (m)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: null
      ymax: null
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: null
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 500 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: ['stabilized']
  # --- Example Heatmap (Time vs Cart Velocity) ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: cart_velocity
    output_filename: fig11_heatmap_time_vs_cart_velocity.png
    config:
      title: Heatmap - Time vs Cart Velocity
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Cart Velocity (m/s)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -6.0
      ymax: 6.0
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: 50000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 500 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Force) ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: force
    output_filename: fig12_heatmap_time_vs_force.png
    config:
      title: Heatmap - Time vs Force
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Force (N)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -45.0
      ymax: 45.0
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: 50000
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 1000 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: null
  # --- Example Heatmap (Time vs Force) stabilized ---
  - type: heatmap
    enabled: true
    source: detailed # Use data from the list of all episode details
    x_variable: time
    y_variable: force
    output_filename: fig13_heatmap_time_vs_force(stabilized).png
    config:
      title: Heatmap - Time vs Force (stabilized)
      title_fontsize: 18
      figsize_w: 14
      figsize_h: 10
      xlabel: Time [s]
      xlabel_fontsize: 16
      ylabel: Force (N)
      ylabel_fontsize: 16
      xmin: null
      xmax: null
      ymin: -8.0
      ymax: 8.0
      tick_fontsize: 14
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      clabel: Frequency
      clabel_fontsize: 14
      cmin: null
      cmax: null
      cmap: hot # 'viridis', 'plasma', 'inferno', 'magma', 'hot', etc.
      bins: 1000 # Number of bins for histogram2d
      log_scale: false # Use logarithmic color scale?
      grid_on: false
      filter_termination_reason: ['stabilized']