data_save:
  json_history:
    enable: true
    json_history_params:
      # System
      - episode
      - time
      - cart_position
      - cart_velocity
      - pendulum_angle
      - pendulum_velocity
      - stability_score
      # Controller
      - kp
      - ki
      - kd
      - force
      - error
      - integral_error
      - derivative_error
      - proportional_term
      - integral_term
      - derivative_term
      ## Agent PID-QLearning
      - id_agent_decision
      - learn_select_duration_ms
      - reward
      - action_kp
      - action_ki
      - action_kd
      - td_error_kp
      - td_error_ki
      - td_error_kd
      - q_value_max_kp
      - q_value_max_ki
      - q_value_max_kd
      #- q_visit_count_state_kp
      #- q_visit_count_state_ki
      #- q_visit_count_state_kd
      #- virtual_reward_kp
      #- virtual_reward_ki
      #- virtual_reward_kd
      #- virtual_stability_score_kp_cf
      #- virtual_stability_score_ki_cf
      #- virtual_stability_score_kd_cf
      #- baseline_value_kp
      #- baseline_value_ki
      #- baseline_value_kd
      #- adaptive_mu_angle
      #- adaptive_sigma_angle
      #- adaptive_mu_angular_velocity
      #- adaptive_sigma_angular_velocity
      #- adaptive_mu_cart_position
      #- adaptive_sigma_cart_position
      #- adaptive_mu_cart_velocity
      #- adaptive_sigma_cart_velocity
      #- patience_M_kp
      #- no_improvement_counter_c_hat_kp
      #- penalty_beta_kp
      #- improvement_metric_value_kp
      #- last_improvement_metric_value_kp
      #- requested_early_termination_kp
      #- patience_M_ki
      #- no_improvement_counter_c_hat_ki
      #- penalty_beta_ki
      #- improvement_metric_value_ki
      #- last_improvement_metric_value_ki
      #- requested_early_termination_ki
      #- patience_M_kd
      #- no_improvement_counter_c_hat_kd
      #- penalty_beta_kd
      #- improvement_metric_value_kd
      #- last_improvement_metric_value_kd
      #- requested_early_termination_kd
  summary:
    enabled: true
    summary_params:
      - episode
      - episode_wall_time_sec
      - final_epsilon
      - final_learning_rate
      - gain_delta
      - total_agent_decisions
      - episode_time_duration_sec
      - termination_reason
      - total_reward
      - performance
      - avg_stability_score 
      - virtual_stability_score_kp_cf
      - virtual_stability_score_ki_cf
      - virtual_stability_score_kd_cf
      - final_kp
      - final_ki
      - final_kd
    summary_statistics: 
      enabled: true
      indicators: ['_mean', 'sigma', '_min', 'p25', 'p50', 'p75', '_max']
      summary_statistics_params:
        - cart_position
        - cart_velocity
        - pendulum_angle
        - pendulum_velocity
        - kp
        - ki
        - kd
        - proportional_term
        - integral_term
        - derivative_term
        - force
        - reward
        - stability_score
        - td_error_kp
        - td_error_ki
        - td_error_kd
        - q_value_max_kp
        - q_value_max_ki
        - q_value_max_kd
        #- virtual_reward_kp
        #- virtual_reward_ki
        #- virtual_reward_kd
        #- virtual_stability_score_kp_cf
        #- virtual_stability_score_ki_cf
        #- virtual_stability_score_kd_cf