plots:
  # --- Example Bar Plot (Termination Reasons) ---
  - type: bar
    enabled: true # Enable/disable this specific plot
    source: summary # Use data from the summary DataFrame
    variable: termination_reason # The column in the summary to count/group by
    output_filename: fig1_termination_reason_distribution.png # Specific output name
    config:
      title: Termination Reason Distribution
      title_fontsize: 28
      figsize_w: 14
      figsize_h: 10
      xlabel: Episode Group [-]
      xlabel_fontsize: 24
      ylabel: Count [-]
      ylabel_fontsize: 24
      # xmin: null # Not typically used for category bar plots
      # xmax: null
      ymin: 0 # Start y-axis at 0
      ymax: null # Auto scale max y
      tick_fontsize: 18
      xtick_rotation: 0
      num_xticks: null # Auto ticks for categories
      num_yticks: null
      show_legend: true
      legend_var: [
                  {value: 'goal_reached', color: '#0077BB', label: 'Goal reached'},
                  {value: 'limit_exceeded', color: '#EE7733', label: 'Limit exceeded'},
                  {value: 'time_limit', color: '#BBBBBB', label: 'Time limit'},
                  {value: 'agent_early_termination', color: '#009988', label: 'Agent patience'}
                ]
      legend_pos: 'lower right' # 'best', 'upper left', 'outside', etc.
      legend_fontsize: 'xx-large' # 'xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large' or a number (e.g., 8, 10, 12)
      grid_on: false
      group_size: 1000 # Size for group by episodes
      cmap: tab20 # Colormap for stacked bars
      bar_width: 0.8
  # --- Example Line Plot (Total Reward) ---
  - type: line
    enabled: false
    source: summary # Use data from the summary DataFrame
    x_variable: episode # Column for x-axis
    y_variable: total_reward # Column for y-axis
    output_filename: fig2_cumulative_reward_per_episode.png
    config:
      title: Cumulative Reward per Episode
      title_fontsize: 28
      figsize_w: 14
      figsize_h: 7
      xlabel: Episode [-]
      xlabel_fontsize: 24
      ylabel: Total Reward [-]
      ylabel_fontsize: 24
      xmin: null # Auto scale min x
      xmax: null # Auto scale max x
      ymin: null # Auto scale min y
      ymax: null # Auto scale max y
      tick_fontsize: 18
      xtick_rotation: 0
      num_xticks: null   # Approx number of desired x-ticks
      num_yticks: null   # Approx number of desired y-ticks
      show_legend: false # Only one line, legend not needed
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.0
      marker_style: 'o' # Style: '.', ',', 'o', 'v', '^', etc. or '' for none
      marker_size: 4
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null # Optional: list like ['goal_reached', 'time_limit'] or null to include all
  # --- Example Line Plot (Episode Time) ---
  - type: line
    enabled: false
    source: summary
    x_variable: episode
    y_variable: time_duration
    output_filename: fig3_episode_duration_per_episode.png
    config:
      title: Episode Duration per Episode
      title_fontsize: 14
      figsize_w: 12
      figsize_h: 6
      xlabel: Episode [-]
      xlabel_fontsize: 12
      ylabel: Duration [s]
      ylabel_fontsize: 12
      xmin: null
      xmax: null
      ymin: 0
      ymax: null
      tick_fontsize: 10
      xtick_rotation: 30
      num_xticks: null
      num_yticks: null
      show_legend: false
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.5
      marker_style: 'o'
      marker_size: 3
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null
  # --- Example Line Plot (Performance) ---
  - type: line
    enabled: false
    source: summary
    x_variable: episode
    y_variable: performance
    output_filename: fig4_performance_per_episode.png
    config:
      title: Performance per Episode
      title_fontsize: 28
      figsize_w: 14
      figsize_h: 7
      xlabel: Episode [-]
      xlabel_fontsize: 24
      ylabel: Performance [-/s]
      ylabel_fontsize: 24
      xmin: null
      xmax: null
      ymin: 0
      ymax: null
      tick_fontsize: 18
      xtick_rotation: 0
      num_xticks: null
      num_yticks: null
      show_legend: false
      legend_pos: best
      grid_on: false
      line_color: "#1f77b4" # Blue
      line_width: 1.0
      marker_style: 'o'
      marker_size: 4
      marker_color: "#ff7f0e" # Orange
      filter_termination_reason: null