data_save:
  config:
    enabled_json_history: true
    enabled_summary: true
    summary_first_cols: [
      'episode', 
      'episode_wall_time_sec', 
      'epsilon', 
      'learning_rate', 
      'gain_delta', 
      'total_agent_decisions', 
      'time_duration', 
      'termination_reason', 
      'total_reward', 
      'performance', 
      'avg_stability_score',
      'final_kp_pendulum_angle', 
      'final_ki_pendulum_angle', 
      'final_kd_pendulum_angle',
      'final_kp_cart_position',
      'final_ki_cart_position',
      'final_kd_cart_position'
      ]
    enabled_summary_stats: true
    statistics_metrics: ['_mean', 'sigma', '_min', 'p25', 'p50', 'p75', '_max']
  components:
    env:
      - {params: 'episode_id', freq: ['on_step'], out: ['json_history', 'summary'], summary_stats: false, alias: 'episode'}
      - {params: 'time', freq: ['on_step'], out: ['json_history'], summary_stats: false}
      - {params: 'time', freq: ['on_final'], out: ['summary'], summary_stats: false, alias: 'time_duration'}
      - {params: 'cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'cart_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'pendulum_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'cart_force', freq: ['on_step'], out: ['json_history'], summary_stats: true}
    controller:
      # --- Controlador de ÁNGULO ---
      - {params: 'kp_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'ki_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'kd_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'kp_pendulum_angle', freq: ['on_final'], out: ['summary'], alias: 'final_kp_pendulum_angle'}
      - {params: 'ki_pendulum_angle', freq: ['on_final'], out: ['summary'], alias: 'final_ki_pendulum_angle'}
      - {params: 'kd_pendulum_angle', freq: ['on_final'], out: ['summary'], alias: 'final_kd_pendulum_angle'}
      - {params: 'raw_action_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'effective_action_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'saturation_error_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'error_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      # --- Controlador de POSICIÓN ---
      - {params: 'kp_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'ki_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'kd_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'kp_cart_position', freq: ['on_final'], out: ['summary'], alias: 'final_kp_cart_position'}
      - {params: 'ki_cart_position', freq: ['on_final'], out: ['summary'], alias: 'final_ki_cart_position'}
      - {params: 'kd_cart_position', freq: ['on_final'], out: ['summary'], alias: 'final_kd_cart_position'}
      - {params: 'raw_action_cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'effective_action_cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'saturation_error_cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'error_cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
    agent:
      - {params: 'action_kp_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history']}
      - {params: 'action_ki_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history']}
      - {params: 'action_kd_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history']}
      - {params: 'action_kp_cart_position', freq: ['on_decision_interval'], out: ['json_history']}
      - {params: 'action_ki_cart_position', freq: ['on_decision_interval'], out: ['json_history']}
      - {params: 'action_kd_cart_position', freq: ['on_decision_interval'], out: ['json_history']}
      
      - {params: 'interval_reward', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      - {params: 'learning_rate', freq: ['on_final'], out: ['summary'], summary_stats: false}
      - {params: 'epsilon', freq: ['on_final'], out: ['summary'], summary_stats: false}

      # --- Errores TD (opcional, pero útil) ---
      #- {params: 'td_error_kp_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      #- {params: 'td_error_ki_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      #- {params: 'td_error_kd_pendulum_angle', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      #- {params: 'td_error_kp_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      #- {params: 'td_error_ki_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
      #- {params: 'td_error_kd_cart_position', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
    stability:
      - {params: 'stability_score', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'avg_stability_score_interval', freq: ['on_decision_interval'], out: ['json_history'], summary_stats: true}
    reward_calc:
      - {params: 'reward', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'reward_base_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'reward_base_pendulum_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_base_cart_position', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'reward_base_cart_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_dp_control_action', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_dp_cart_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'reward_di_lineal_pendulum_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_di_tanh_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'target_pendulum_angle', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_di_tanh_pendulum_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'target_pendulum_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'reward_di_tanh_cart_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'target_cart_velocity', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'fixed_penalty', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'reward_penalty_delta_control_action', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      # {params: 'quadratic_penalty_reward', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      - {params: 'goal_bonus', freq: ['on_step'], out: ['json_history'], summary_stats: true}
      #- {params: 'bandwidth_bonus', freq: ['on_step'], out: ['json_history'], summary_stats: true}
    sim_manager:
      - {params: 'id_agent_decision', freq: ['on_step'], out: ['json_history']} # *Dejar como 'on_step' para registrar en cada paso
      - {params: 'total_agent_decisions', freq: ['on_final'], out: ['summary']}
      - {params: 'episode_wall_time_sec', freq: ['on_final'], out: ['summary']}
      - {params: 'termination_reason', freq: ['on_final'], out: ['json_history', 'summary']}